version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mabel_db
    environment:
      POSTGRES_USER: mabel_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: mabel_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: